---
apiVersion: v1
kind: Template
labels:
  template: "networksecurity-template"
objects:
  - kind: NetworkSecurityPolicy
    apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
    metadata:
      name: "any-pods-to-egress-${NAMESPACE}"
    spec:
      description: |
        Allow the builds to access the internet.
      source:
        - - $namespace=${NAMESPACE}
      destination:
        - - ext:network=any
  - kind: NetworkSecurityPolicy
    apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
    metadata:
      name: "any-pods-to-any-pods-${NAMESPACE}"
    spec:
      description: |
        Allow the namespace to talk to itself
      source:
        - - $namespace=${NAMESPACE}
      destination:
        - - $namespace=${NAMESPACE}
  - kind: NetworkSecurityPolicy
    apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
    metadata:
      name: "any-pods-to-k8s-api-${NAMESPACE}"
    spec:
      description: |
        Allow pods to talk to the internal api so deployments work.
      source:
        - - $namespace=${NAMESPACE}
      destination:
        - - int:network=internal-cluster-api-endpoint
parameters:
  - name: NAMESPACE
    description: OpenShift namespace containing our image to deploy (ex. idcqvl-dev)
    required: true
